"""Declarative base and shared column conventions for every APIx table.

One base, one metadata object, one naming convention. Alembic autogenerate compares
against this metadata, so anything not reachable from here does not exist.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import Enum as PyEnum
from typing import TYPE_CHECKING, Any

from sqlalchemy import Date, DateTime, MetaData, Numeric, String, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

if TYPE_CHECKING:
    from collections.abc import Sequence

# Deterministic constraint names. Without these, Alembic emits unnamed constraints
# that cannot be dropped by a later forward-only migration.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 — SQLAlchemy reads this as a plain dict
        dict[str, Any]: JSONB,
        list[str]: JSONB,
        datetime: DateTime(timezone=True),
        date: Date,
        Decimal: Numeric(14, 6),
        uuid.UUID: UUID(as_uuid=True),
        str: String,
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """A server-generated UUID primary key.

    Generated by the database (``gen_random_uuid()``, pgcrypto/PG13+) so that an id
    exists the moment the row lands, independent of which process inserted it.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at_col() -> Mapped[datetime]:
    """Row-creation timestamp, always timezone-aware, set by the database clock."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )


# Money. Fares are stored to two decimal places in the currency of the quote.
Money = Numeric(12, 2)

# Index values. Six decimal places: enough that rebasing and chaining do not
# accumulate visible rounding error in a published series.
IndexNumber = Numeric(14, 6)


def pg_enum(python_enum: type[PyEnum], name: str) -> SAEnum:
    """A native PostgreSQL enum type with an explicit, stable name.

    Two things are pinned deliberately:

    * ``name`` — SQLAlchemy would otherwise derive it from the class name
      (``CarrierType`` -> ``carriertype``). Migrations reference these types by name for
      the life of the database, so the name is spelled out rather than inferred.
    * ``values_callable`` — SQLAlchemy stores enum *names* by default. APIx stores
      *values*, because some of them are published code lists (``Frequency.MONTHLY`` is
      the SDMX code ``M``, not the string ``MONTHLY``).
    """
    return SAEnum(
        python_enum,
        name=name,
        native_enum=True,
        create_type=True,
        validate_strings=True,
        values_callable=_enum_values,
    )


def _enum_values(python_enum: type[PyEnum]) -> Sequence[str]:
    return [str(member.value) for member in python_enum]
