"""Controlled vocabularies used by the data model.

These are stored as native PostgreSQL enums. A value that is not in one of these lists
cannot enter the database — which is the point: a statistical office cannot audit a
free-text ``status`` column.
"""

from __future__ import annotations

from enum import StrEnum


class CarrierType(StrEnum):
    """Airline business model. Drives stratification of the elementary aggregates."""

    FSC = "FSC"  # full-service carrier
    LCC = "LCC"  # low-cost carrier
    REGIONAL = "REGIONAL"
    CHARTER = "CHARTER"


class SourceType(StrEnum):
    """What kind of site a source is. Determines which collector handles it."""

    AIRLINE = "AIRLINE"  # carrier's own website
    OTA = "OTA"  # online travel agent
    METASEARCH = "METASEARCH"
    GDS = "GDS"  # licensed distribution feed
    OFFICIAL = "OFFICIAL"  # DGCA / MoSPI published data
    SYNTHETIC = "SYNTHETIC"  # generated by apix_core.testing — never collected data


class CollectionMethod(StrEnum):
    """How a quote was obtained. Recorded on every quote for auditability."""

    STATIC_HTML = "STATIC_HTML"
    RENDERED_PAGE = "RENDERED_PAGE"
    PUBLIC_JSON_API = "PUBLIC_JSON_API"
    PARTNER_FEED = "PARTNER_FEED"
    FIXTURE = "FIXTURE"  # recorded response — tests and replays only
    SYNTHETIC = "SYNTHETIC"  # generated in-process; no response ever existed


class LegalBasis(StrEnum):
    """Why we were entitled to collect this quote.

    Every quote carries one. A quote whose basis cannot be established is not collected.
    """

    ROBOTS_ALLOWED = "ROBOTS_ALLOWED"
    TOS_PERMITTED = "TOS_PERMITTED"
    CONTRACTUAL = "CONTRACTUAL"  # signed data agreement with the source
    OFFICIAL_PUBLICATION = "OFFICIAL_PUBLICATION"
    FIXTURE = "FIXTURE"
    SYNTHETIC = "SYNTHETIC"  # our own generated data; nothing was collected


class TosVerdict(StrEnum):
    """Outcome of a human review of a source's terms of service."""

    PERMITTED = "PERMITTED"
    PROHIBITED = "PROHIBITED"
    AMBIGUOUS = "AMBIGUOUS"  # treated as PROHIBITED until a human resolves it
    NOT_REVIEWED = "NOT_REVIEWED"


class PolicyDecisionOutcome(StrEnum):
    """What the PolicyEngine decided about a specific URL."""

    ALLOWED = "ALLOWED"
    DENIED_ROBOTS = "DENIED_ROBOTS"
    DENIED_TOS = "DENIED_TOS"
    DENIED_RATE_LIMIT = "DENIED_RATE_LIMIT"
    DENIED_PATH = "DENIED_PATH"
    DENIED_SOURCE_DISABLED = "DENIED_SOURCE_DISABLED"
    DENIED_CAPTCHA = "DENIED_CAPTCHA"  # a challenge was seen; we stop, never solve


class RunStatus(StrEnum):
    """Lifecycle of a collection run or an index run."""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"  # completed, but with recorded gaps — still publishable data
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"  # stopped by policy, not by error


class FareClass(StrEnum):
    """Cabin. Not the booking class letter, which lives in ``fare_brand``."""

    ECONOMY = "ECONOMY"
    PREMIUM_ECONOMY = "PREMIUM_ECONOMY"
    BUSINESS = "BUSINESS"
    FIRST = "FIRST"


class Frequency(StrEnum):
    """Series periodicity, aligned with the SDMX code list."""

    DAILY = "D"
    WEEKLY = "W"
    MONTHLY = "M"
    QUARTERLY = "Q"
    ANNUAL = "A"
