"""Plot the synthetic dataset's fare curves — `make synthetic-curves`.

Regenerates the dataset in memory from ``config/synthetic.yaml`` (no database needed,
same seed, so these figures describe exactly what ``make seed-synthetic`` loads) and
writes four panels to ``docs/synthetic/``:

* lead-time curves per route — the booking curve the index engine must handle;
* the configured advance-purchase multiplier against the realised median, showing the
  emergent curve tracks its parameters;
* a travel-date fare series showing weekly sawtooth and festival peaks;
* the share of sold-out (genuinely missing) cells by days before departure.

All of it is SYNTHETIC scenario data; every figure says so on its face.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import structlog

from apix_core.config import load_basket, load_synthetic
from apix_core.seeding import load_airport_coords
from apix_core.testing.synthetic import generate, lead_time_multipliers

log = structlog.get_logger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "docs" / "synthetic"
START = date(2026, 6, 7)  # the window `make seed-synthetic DAYS=90` used on 2026-09-04
DAYS = 90
SHOW_ROUTES = ["DEL-BOM", "DEL-BLR", "BOM-CCU", "DEL-SXR", "BLR-COK", "DEL-GAU"]
WATERMARK = "SYNTHETIC scenario data — generated by apix_core.testing, not collected"


def _stamp(fig: plt.Figure) -> None:
    fig.text(0.5, 0.005, WATERMARK, ha="center", fontsize=8, color="crimson")


def main() -> int:
    cfg = load_synthetic()
    basket = load_basket()
    coords = load_airport_coords(REPO_ROOT / "db" / "seeds")
    dataset = generate(cfg, basket, coords, START, DAYS)
    quotes = dataset.quotes
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- 1. lead-time curves per route ------------------------------------------
    fig, ax = plt.subplots(figsize=(9, 6))
    for route in SHOW_ROUTES:
        sub = quotes[quotes["route_code"] == route]
        med = sub.groupby("advance_days")["total_fare"].median().sort_index()
        ax.plot(med.index, med.to_numpy(), marker="o", label=route)
    ax.invert_xaxis()
    ax.set_xlabel("days before departure")
    ax.set_ylabel("median total fare (INR)")
    ax.set_title(f"Synthetic lead-time curves by route ({DAYS} collection days)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    _stamp(fig)
    fig.savefig(OUT_DIR / "lead_time_by_route.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    # --- 2. configured multiplier vs realised median ----------------------------
    adv_grid = np.array(sorted(quotes["advance_days"].unique()), dtype=np.int64)
    configured = lead_time_multipliers(cfg, adv_grid)
    realised = (
        quotes.groupby("advance_days")["base_fare"].median()
        / quotes[quotes["advance_days"] == 45]["base_fare"].median()
    ).sort_index()
    fig, ax = plt.subplots(figsize=(9, 6))
    ax.plot(
        adv_grid,
        configured / configured[np.searchsorted(adv_grid, 45)],
        "k--",
        label="configured knot curve (rel. T+45)",
    )
    ax.plot(
        realised.index,
        realised.to_numpy(),
        marker="o",
        label="realised median base fare (rel. T+45)",
    )
    ax.invert_xaxis()
    ax.set_xlabel("days before departure")
    ax.set_ylabel("multiplier relative to T+45")
    ax.set_title("Advance-purchase curve: parameters vs emergent prices")
    ax.legend()
    ax.grid(True, alpha=0.3)
    _stamp(fig)
    fig.savefig(OUT_DIR / "lead_time_vs_config.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    # --- 3. travel-date series: weekly sawtooth + festivals ---------------------
    window = quotes[quotes["advance_days"].isin([18, 26])]
    series = window.groupby("travel_date")["total_fare"].median()
    fig, ax = plt.subplots(figsize=(11, 6))
    ax.plot(series.index, series.to_numpy(), lw=1.2)
    for festival in cfg.festivals:
        if series.index.min() <= festival.date <= series.index.max():
            ax.axvline(festival.date, color="orange", alpha=0.6, ls=":")
            ax.annotate(
                festival.name,
                (festival.date, series.max()),
                rotation=90,
                fontsize=7,
                va="top",
                ha="right",
                color="darkorange",
            )
    ax.set_xlabel("travel date")
    ax.set_ylabel("median total fare (INR), booked 18-26 days out")
    ax.set_title("Weekly and festival seasonality on the travel date")
    ax.grid(True, alpha=0.3)
    fig.autofmt_xdate()
    _stamp(fig)
    fig.savefig(OUT_DIR / "seasonality.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    # --- 4. sell-out missingness by days-out ------------------------------------
    observed = quotes.drop_duplicates(
        subset=["route_code", "flight_number", "query_date", "travel_date"]
    )["advance_days"].value_counts()
    missing = dataset.sold_out["advance_days"].value_counts()
    frame = (missing / (missing.add(observed, fill_value=0))).fillna(0).sort_index() * 100
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.bar(frame.index.astype(str), frame.to_numpy(), color="steelblue")
    ax.set_xlabel("days before departure")
    ax.set_ylabel("% of flight-days sold out (missing quotes)")
    ax.set_title("Genuinely missing observations from bucket sell-outs")
    ax.grid(True, axis="y", alpha=0.3)
    _stamp(fig)
    fig.savefig(OUT_DIR / "sell_out_missingness.png", dpi=150, bbox_inches="tight")
    plt.close(fig)

    log.info(
        "synthetic_curves_written",
        out_dir=str(OUT_DIR),
        quotes=len(quotes),
        sold_out=len(dataset.sold_out),
        anomalies=len(dataset.anomalies),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
